name: test

on:
  pull_request:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: clean
        run: go clean && go clean -cache
      - name: build
        run: go build .
  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: set up docker environment
        run: docker compose up -d
      - name: clean
        run: go clean && go clean -cache
      - name: test
        run: go test -p 1 -count 1 -v ./...
      - name: clean docker environment
        run: docker compose down --rmi all -v --remove-orphans

